### ISSUE TITLE
imagenet_tutorial_fgsm_pytorch.py报错

### ISSUE THREAD

**Issue by weitianli** [baidu/AdvBox#15]
`imagenet_tutorial_fgsm_pytorch.py[line:52] INFO CUDA Available: True cuda
pytorch.py[line:63] INFO Finish PytorchModel init
(1, 3, 224, 224)
Traceback (most recent call last):
  File "imagenet_tutorial_fgsm_pytorch.py", line 132, in <module>
    main("cropped_panda.jpg")
  File "imagenet_tutorial_fgsm_pytorch.py", line 108, in main
    adversary = attack(adversary, **attack_config)
  File "../advbox/attacks/base.py", line 47, in __call__
    self._preprocess(adversary)
  File "../advbox/attacks/base.py", line 72, in _preprocess
    self.model.predict(adversary.original))
  File "../advbox/models/pytorch.py", line 86, in predict
    predict = np.squeeze(predict, axis=0)
  File "/home/.../anaconda3/envs/bdbox/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 1292, in squeeze
    return squeeze(axis=axis)
TypeError: squeeze() missing 1 required positional arguments: "dim"
`
按照官方的实例运行，环境也是按照requirement安装的，出现了这个squeeze()的问题。

**Comment by weitianli** [comment]
1.15.4

**Comment by duoergun0729** [comment]
你看下我的requrement 不是这个版本  pip install numpy==1.14.5试试把
